from enum import Enum
from typing import Callable, Any

class NanEyeSensorType(Enum):
    NanEye2D = "NanEye2D"
    NanEyeM = "NanEyeM"
    NanEyeXS = "NanEyeXS"

class SensorChannel(Enum):
    CH1 = "CH1"
    CH2 = "CH2"
    BOTH = "BOTH"

class Camera:
    def __init__(self, sensorType: NanEyeSensorType) -> None: ...
    def GetLastFrame(self) -> Any: ...
    def StartCapture(self) -> None: ...
    def StopCapture(self) -> None: ...
    def SetExposure(self, value: int) -> None: ...
    def SetOffset(self, value: int) -> None: ...
    def SetGain(self, value: int) -> None: ...
    def SetFrameRate(self, value: int) -> None: ...
    def SubscribeToImageProcessedEvent(self, e: Callable) -> None: ...
    def EnableAutomaticExposureControl(self) -> None: ...
    def DisableAutomaticExposureControl(self) -> None: ...
    def ReconfigureAutomaticExposureControl(self) -> None: ...
    def EnableColourReconstruction(self) -> None: ...
